version: '3.8'

services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped

x-casaos:
  icon: https://icon.casaos.io/main/all/redis.png
  port_map: "5540"
  scheme: http
  title:
    custom: Redis Insight
    en_us: redis-insight
